# Generated by Django 2.2.7 on 2020-02-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='type',
            new_name='timeFrame',
        ),
    ]
