# Generated by Django 2.2.7 on 2020-02-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200206_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minute',
            field=models.CharField(max_length=20),
        ),
    ]
