# Generated by Django 2.2.7 on 2020-02-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200206_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='openP',
            new_name='open',
        ),
    ]
