# Generated by Django 2.2.7 on 2020-02-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200206_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('timeFrame', 'date', 'minute')},
        ),
    ]
