# Generated by Django 2.2.7 on 2020-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20200208_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='minute',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol', 'timeFrame', 'date', 'minute')},
        ),
    ]
