# Generated by Django 2.2.7 on 2020-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20200208_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='minute',
            field=models.CharField(max_length=20),
        ),
    ]
