# Generated by Django 2.2.7 on 2020-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20200208_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(null=True),
        ),
    ]
