# Generated by Django 2.2.7 on 2020-02-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200206_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='average',
        ),
    ]
