# Generated by Django 2.2.7 on 2020-02-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stock_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='open',
            new_name='openP',
        ),
    ]
