# Generated by Django 2.2.7 on 2020-02-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200206_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol', 'timeFrame', 'date', 'minute')},
        ),
    ]
