# Generated by Django 2.2.7 on 2020-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20200208_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(default=-1),
        ),
    ]
