# Generated by Django 2.2.7 on 2020-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20200208_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(default=-1),
        ),
    ]
