# Generated by Django 2.2.7 on 2020-02-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20200208_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.FloatField(null=True),
        ),
    ]
