# Generated by Django 2.2.7 on 2020-02-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20200208_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='currency',
            new_name='dataType',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timeFrame',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol', 'timeFrame', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('exchange', 'dataType', 'symbol')},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='region',
        ),
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFrame', models.CharField(max_length=4)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Symbol')),
            ],
            options={
                'unique_together': {('symbol', 'timeFrame', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFrame', models.CharField(max_length=4)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Symbol')),
            ],
            options={
                'unique_together': {('symbol', 'timeFrame', 'date')},
            },
        ),
    ]
