# Generated by Django 2.2.7 on 2020-02-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20200208_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crypto',
            unique_together={('symbol', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='forex',
            unique_together={('symbol', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol', 'date')},
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='timeFrame',
        ),
        migrations.RemoveField(
            model_name='forex',
            name='timeFrame',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='timeFrame',
        ),
    ]
