# Generated by Django 2.2.7 on 2020-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20200208_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
