# Generated by Django 2.2.5 on 2020-05-04 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20200208_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
